version: '3'
services:

  web:
    build:
      context: .
      dockerfile: .docker/web/Dockerfile
    ports:
      - 80:80
    volumes:
      - .:/var/www/html

  node:
    build:
      context: .
      dockerfile: .docker/node/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/home/node/app
    user: "node"
    working_dir: /home/node/app

  mysql:
    build:
      context: .
      dockerfile: .docker/mysql/Dockerfile
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=eventApp_DB"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=root"
      - "MYSQL_ROOT_PASSWORD=root"
    ports:
        - "33061:3306"
